# Example Site settings

#google_analytics: UA-NNNNNNNN-N

header_pages:
  - index.md
  - kavar.md
  

footer: ''

style: dark
#listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
